# Default values for k8s-humio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: humio/humio
  tag: 1.0.69
  pullPolicy: IfNotPresent

humio:
  jvmArgs: "-Xss2M -XX:MaxDirectMemorySize=4G"
  authenticationMethod: none

resources:
  cpuLimit: 2000m
  cpuRequest: 1000m
  memoryLimit: 6144Mi
  memoryRequest: 2048Mi