apiVersion: v1
kind: Service
metadata:
  name: "{{ template "k8s-humio.name" . }}-es"
  labels:
    app: {{ template "k8s-humio.name" . }}
    chart: {{ template "k8s-humio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: es
  selector:
    app: {{ template "k8s-humio.name" . }}
    release: {{ .Release.Name }}
